### ISSUE TITLE
Rodent3D dataset

### ISSUE THREAD

**Issue by SunKai-Tsinghua** [mahir1010/OptiPose#1]
Hello, how to get the extrinsic camera parameters of the three depth cameras in the Rodent3D dataset?

**Comment by mahir1010** [comment]
You can use something like [this](https://gist.github.com/mahir1010/d4a6f7c117eb2c74b14a616840e87411) to convert DLT coefficients to camera parameters. You have to convert the provided YAML file into the valid EasyWand format [(Details found here)](https://www.cs.bu.edu/faculty/betke/jeb/EasyWand_Documentation.pdf).
If you have time constraints, you can convert them, but I will try to upload the converted parameters over the next few weeks.

Please note that the calibration parameters were generated assuming the image is created behind the camera. Before running the point-cloud registration algorithm, you must flip the depth data across the X-Y plane.

Please send me an email if you have questions about the dataset, and please keep this reserved for OptiPose-related queries.
